name: Simple Pipe

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: greetings-jar
        path: build/libs
  test-run:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download candidate artifacts
      uses: actions/download-artifact@v2
      with:
        name: greetings-jar
    - shell: bash
      run: |
        java -jar greetings-actions.jar ${{ github.event.inputs.myValues  }}      

  count-args:
    runs-on: ubuntu-latest
    steps:
    - id: report-count
      uses: chostrander/arg-count-action@Main
      with:
        arguments-to-count: ${{ github.event.inpouts.myValues }}
    - run: echo
    - shell: bash
      run: |
        echo argument count is ${{ steps.report-count.outputs.arg-count }}
